version: '3'

services:
  jeff:
    image: ghcr.io/janitorjeff/jeff-bot:main
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - VIRTUAL_HOST=localhost
      - PORT=5000
      # DB
      - POSTGRES_USER=jeff_user
      - POSTGRES_PASSWORD=jeff_pass
      - POSTGRES_DB=jeff_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=6000
      - POSTGRES_SSLMODE=disable
      - REDIS_ADDR=redis:7000
      # Frontends
      - DISCORD_TOKEN=token
      - TWITCH_CHANNELS=comma,seperated,list,of,channel,names
      - TWITCH_CLIENT_ID=cliend-id
      - TWITCH_CLIENT_SECRET=client-secret
      - TWITCH_OAUTH=oauth-token
      # Commands
      - MIN_GOD_INTERVAL_SECONDS=600
      - OPENAI_KEY=api-key
      - TIKTOK_SESSION_ID=session-id
      - YOUTUBE=token
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres
    restart: unless-stopped
    expose:
      - "6000"
    environment:
      - POSTGRES_USER=jeff_user
      - POSTGRES_PASSWORD=jeff_pass
      - POSTGRES_DB=jeff_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: -p 6000

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000

volumes:
  postgres-data:
