version: '3'

services:
  jeff:
    image: ghcr.io/janitorjeff/jeff-bot:main
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres
    ports:
      - "6000"
    environment:
      - POSTGRES_USER=jeff
      - POSTGRES_PASSWORD=jeff
      - POSTGRES_DB=jeff
    volumes:
      - ./db-data:/var/lib/postgresql/data
    command: -p 6000

  redis:
    image: redis
    ports:
      - "7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000

volumes:
  db-data:
