version: '3'

services:
  jeff:
    image: ghcr.io/janitorjeff/jeff-bot:main
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DOMAIN=localhost
      - PORT=5000
      - DISCORD_TOKEN=token
      - MIN_GOD_INTERVAL_SECONDS=600
      - OPENAI_KEY=api-key
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=host
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=port
      - POSTGRES_SSLMODE=disable
      - POSTGRES_USER=user
      - REDIS_ADDR=host:port
      - TIKTOK_SESSION_ID=session-id
      - TWITCH_CHANNELS=comma,seperated,list,of,channel,names
      - TWITCH_CLIENT_ID=cliend-id
      - TWITCH_CLIENT_SECRET=client-secret
      - TWITCH_OAUTH=oauth-token
      - YOUTUBE=token
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres
    ports:
      - "6000"
    environment:
      - POSTGRES_USER=jeff
      - POSTGRES_PASSWORD=jeff
      - POSTGRES_DB=jeff
    volumes:
      - ./db-data:/var/lib/postgresql/data
    command: -p 6000

  redis:
    image: redis
    ports:
      - "7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000

volumes:
  db-data:
